In [26]:
import arkouda as ak
import numpy as np

In [27]:
ak.connect(connect_url='tcp://andrej-X556UQ:5555')

connected to arkouda server tcp://*:5555


In [28]:
N = 10
a1 = ak.ones(N,dtype=np.int64)
a2 = ak.arange(0,N,1)
t1 = a1
t2 = a1 * 10
dt = 10
print(a1)
print(a2)
g2 = ak.GroupBy(a2)

[1 1 1 1 1 1 1 1 1 1]
[0 1 2 3 4 5 6 7 8 9]


In [29]:
print(g2)
I,J = ak.join_on_eq_with_dt(a1,a2,t1,t2,dt,"true_dt")
nl = ak.get_config()['numLocales']
print(I)
print(J)

[0 5 1 6 7 2 3 8 4 9]
[1 1 1 1 1 1 1 1 1 1]


In [17]:
print(I)
print(J)

[1 1 1 ... 1 1 1]
[0 1 2 ... 997 998 999]


In [26]:
b = b*3

Uncaching  id_1
New cache length  1
binopvsStore:
create with name id_14 id_1


In [27]:
print(b)

cmd= binopvsStore
id_14   id_1
cmd= str
Caching  id_3
[0 3 6 9 12]
